### ISSUE TITLE
Gotify - Rocketchat

### ISSUE THREAD

**Issue by githubdeb** [immanuelfodor/immanuelfodor#1]
Hi Immanuel,

I try to setup gotify to work with rocketchat. Cam you help me? I am a beginner in this area.
1. I have installed rockectchat and used my gotify gateway for push notifications like this: https://push.mydomain.com/my_app_token
2. I have created users to use gotify with username and passsword.
3. I have installed Gotify.apk on two android phones and successfully logged in to my gotify server(https://push.mydomain.com
4. I was expecting to see a notification on Gotify when I use rocketchat and the other user is logged in but with the app closed. However, I do not see anything.
5. Can you please explain me where I'm wrong and how should I solve this problem step by step?
Thank you.
Luke

**Comment by immanuelfodor** [comment]
Thanks for the question, would you be so kind to reopen this issue in the related repo? It could help others if they look into it later but it's not so obvious to find it in a general profile repo. Just copypaste it over here, please: https://github.com/immanuelfodor/rocketchat-push-gateway
